### ISSUE TITLE
Your lib can't coexist with other dependencies including support-v4

### ISSUE THREAD

**Issue by theGlenn** [Insiteo/Android#1]
Hi,
I tried to add  `compile('com.google.android.gms:play-services:6.5.87')`  to your sample-project app module build.gradle file and it throws this error :

```
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Landroid/support/v4/app/BackStackState;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)
```

The fact is that you lib don't even build itself with the classic support library `compile 'com.android.support:support-v4:18.0.+'`, something might be wrong with the way support-v4 is included into your library. By the way excluding the module from it doesn't work too.

```
compile (project(':lbsLib-release')){
        exclude module: 'support-v4'
    }
```

**Comment by mathieu-morel** [comment]
Hi,

Thank you for your comment. This is a known issue that will be fixed in a future release. 

I am not sure but using the exclude (http://www.gradle.org/docs/current/userguide/dependency_management.html#sub%3aexclude_transitive_dependencies) option in your build.gradle could be a work around for now.

**Comment by theGlenn** [comment]
Hi,

I tried some exclusion strategy but it does not work at all, the things is that under : `app/build/intermediates/exploded-aar/projectName/IbsLib-Release/unspecified/classes.jar` there is an included `android.support.v4` file like you can see below.

![capture d ecran 2015-01-15 a 11 18 26](https://cloud.githubusercontent.com/assets/3216616/5755748/68864f00-9ca8-11e4-8e2c-4f6cc8e8e88e.png)

**Comment by mathieu-morel** [comment]
Hi,

Another workaround would be to use this support-v4 (the one included in our library) and may be exclude the one from all other librairies. It could fix the issue temporarily.

We are currently working on the next release of this version. It should be available pretty soon.

**Comment by theGlenn** [comment]
I tried but the things is that this file is not in the build graph. It is not accessible by others libraries.
When running `./gradlew app:dependencies` it is not listed as a dependency. 
I think the file is included as a plain `*.jar` file into your root project rather than just being a gradle dependendy so it is used by your library as a local file.

**Comment by mathieu-morel** [comment]
Yes the <code>support-v4</code> is indeed included as a plain <code>*.jar</code>, it comes from the import of the Eclipse project to Android Studio but I thought that the exclude could work.

I'll let you know when the next release is available.

**Comment by theGlenn** [comment]
Ok thanks for your reactivity. 
:+1:

**Comment by theGlenn** [comment]
:+1:
