### ISSUE TITLE
Conflict on Lcom/google/protobuf/AbstractMessage

### ISSUE THREAD

**Issue by theGlenn** [Insiteo/Android#2]
Hey ! 

New issue :8ball: 

Now I Have the error below, which is weird because I've setted up the same buid.gradle in your test project and it works, any idea ?

```
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/protobuf/AbstractMessage$1;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)
```

The build.gradle

```
    compile 'com.android.support:support-v4:21.0.+'

    compile('com.google.android.gms:play-services:6.5.87') {
        exclude group: 'com.google.android', module: 'support-v4'
    }

    compile project(':lbsLib-3.3.0_RC1-release')
```

Even testing with doesn't work.

```
    compile (project(':lbsLib-3.3.0_RC1-release')){
        exclude group: 'com.google.android', module: 'support-v4'
    }
```

**Comment by mathieu-morel** [comment]
Hi,

It seems to be a dependency conflict on some protocol buffer libraries. Do you have any other libraries you are refering to that could cause this conflict (It will explain why the compilation succeed in the SampleApp) ?

**Comment by theGlenn** [comment]
No,

I'm only refering to the google GMS with `'com.google.android.gms:play-services:6.5.87'` and it does not have Protocol Buffers as a dependency

**Comment by theGlenn** [comment]
Ok just tried by building a fresh new clean, empty, void, project. :+1: 
I imported the `lbsLib-3.3.0_RC1-release.arr` and filled the fresh soft-generated `build.gradle` :+1:  and the problem occurred again... I'm really wondering why it does only works in your test project. Maybe you did included it in a specific way or something.

Here is the dependencies for  the `build.gradle` : 

```
dependencies {
   compile fileTree(dir: 'libs', include: ['*.jar']) 
   compile 'com.android.support:support-v4:21.0.+'
   compile project(':lbsLib-3.3.0_RC1-release')
}
```

**Comment by mathieu-morel** [comment]
I have probably found a fix for this issue. I will try to provide a new version tomorrow. I'll let you know when it's available.

**Comment by theGlenn** [comment]
OK thank you !
 I'll be waiting for it.

**Comment by mathieu-morel** [comment]
I have just commited a <code>3.3.0_RC1_VC2</code> that should fixed the issues you encountered. I had it running in a fresh project (with all your dependencies) and in the <code>SampleApp</code>.

You will probably face warnings during the build process. They come from the proguard step and should not be of any concerns.

**Comment by theGlenn** [comment]
OK nice it works now I close this issue ;)

**Comment by RajeshChandrasekaran** [comment]
Mathieu,

I am facing the same issue while using official release 3.3.0. Following are the dependencies in build.gradle

compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.google.android.gms:play-services:6.5.87'
    compile 'com.ibm.mobile.services:ibmpush:1.+'
    compile 'com.ibm.mobile.services:ibmcloudcode:1.+'
    compile 'com.ibm.mobile.services:ibmdata:1.+'
    compile 'com.ibm.mobile.services:ibmbluemix:1.+'
    compile 'com.ibm.mobile.services:ibmfilesync:1.+'
    compile 'com.pkmmte.view:circularimageview:1.1'
    compile 'com.google.code.gson:gson:2.3.1'
    compile('de.keyboardsurfer.android.widget:crouton:1.8.5@aar') {
        exclude group: 'com.google.android', module: 'support-v4'
    }
    compile project(':lbsLib-3.3.0')

Getting the error while running the app
com.android.dex.DexException: Multiple dex files define Lcom/google/protobuf/AbstractMessage$1;

Your recommendation will be really helpful

Thanks.
