### ISSUE TITLE
In official release 3.3.0 - Issue same as reported by Glenn Multiple dex files define Lcom/google/protobuf/AbstractMessage

### ISSUE THREAD

**Issue by RajeshChandrasekaran** [Insiteo/Android#6]
Mathieu,

I am facing the same issue while using official release 3.3.0. Following are the dependencies in build.gradle

compile fileTree(dir: 'libs', include: ['*.jar'])
compile 'com.android.support:appcompat-v7:21.0.3'
compile 'com.google.android.gms:play-services:6.5.87'
compile 'com.ibm.mobile.services:ibmpush:1.+'
compile 'com.ibm.mobile.services:ibmcloudcode:1.+'
compile 'com.ibm.mobile.services:ibmdata:1.+'
compile 'com.ibm.mobile.services:ibmbluemix:1.+'
compile 'com.ibm.mobile.services:ibmfilesync:1.+'
compile 'com.pkmmte.view:circularimageview:1.1'
compile 'com.google.code.gson:gson:2.3.1'
compile('de.keyboardsurfer.android.widget:crouton:1.8.5@aar') {
exclude group: 'com.google.android', module: 'support-v4'
}
compile project(':lbsLib-3.3.0')

Getting the error while running the app
com.android.dex.DexException: Multiple dex files define Lcom/google/protobuf/AbstractMessage$1;

Your recommendation will be really helpful

Thanks.

**Comment by mathieu-morel** [comment]
RajeshChandrasekaran,

It looks like during the API generation the libraries <code>.jar</code> file have been embedded twice. I will generate those API asap. A work around  would be to delete all the <code>.jar</code> from the lib folder of the <code>lbsLib-3.3.0.aar</code>. This way you should be able to use the API until I publish a fixed version.

**Comment by RajeshChandrasekaran** [comment]
Removing the lib folder from .aar solves the issue. Please update once the fixed version of API is available.

Thanks for the quick response.

**Comment by mathieu-morel** [comment]
RajeshChandrasekaran,

I have just released the 3.3.0_vc2 version of the API. It contains the fix for the <code>Multiple DEX file issue</code>.

**Comment by RajeshChandrasekaran** [comment]
Hi Mathieu,

We are computing the itinerary between the current location of the user and selected destination room using computeItinerary() method. There is no problem in computation, but the map displayed is that of the destination location and not the one where the user is currently standing.

How to display (and dynamically change) the map where user is located during itinerary?

Thanks,
Rajesh Chandrasekaran.
